site_name: 我的文档网站
theme:
  name: material
  language: zh
  palette:
    primary: teal
    accent: pink
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
nav:
- index: index.md
- 未命名: 未命名.md
- '408':
  - 大纲: 408\大纲.md
- 计网:
  - 大纲: 408\计网\大纲.md
