site_name: 我的文档网站

theme:
  name: material  # 指定主题
  language: zh    # 中文界面
  palette:        # 自定义配色（可选）
    primary: teal
    accent: pink

markdown_extensions:
  - pymdownx.highlight  # 代码高亮
  - pymdownx.superfences

nav:
  - 首页: index.md
  - 408: 未命名.md